# Generated by Django 5.1 on 2024-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simple_User",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        max_length=6, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250, unique=True)),
                ("password", models.CharField(max_length=250)),
            ],
        ),
    ]
