# Generated by Django 5.1 on 2024-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_delete_simple_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
