# Generated by Django 5.1 on 2024-08-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
