# Generated by Django 5.1 on 2024-08-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
