# Generated by Django 5.1 on 2024-08-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.IntegerField(default=0)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
