# Generated by Django 5.1 on 2024-08-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="user_id",
            new_name="user",
        ),
    ]
